.\" to view this file: $ man ./README.7
.Dd September 26, 2025
.Dt README.7
.Os "joe <rbo@gmx.us>"
.
.Sh NAME
.Nm halfcab
.Nd backscreen LEDs controller
.
.Sh DESCRIPTION
halfcab is a Linux/BSD tool to control ambient LEDs lighting using an ESP8266.
.
.Pp
halfcab is not quite forked but heavily inspired of
.Lk https://github.com/josh26turner/Ambilight josh26turner/Ambilight ,
it uses a lot of similar code.
